[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "12a7b52ce9286de5621792ee39cd419759609804"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "30eb1e00a8cafde74a3d61f62eeaec13d550aaa3082c7bd74abccb775e0a1b20"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.8+0/UnoUtils.v2026.2.8.aarch64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "04d219affdbe72abba5f5b228b340c4b25ffa408"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "049ab2d9ffc64624c6e5242b1d0a538f756c2518d963f5f195bcde3b977f6531"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.8+0/UnoUtils.v2026.2.8.aarch64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "2baf870731cf96eceb1cd3c4cbd539eb70d8c963"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "b921fb1fe795cf0c693ca6b85fd03f22be7581fac4a70a65435ff2039411e4a5"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.8+0/UnoUtils.v2026.2.8.x86_64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "bc04c03c36fae862b84c037c2749ae684e7a18ee"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "078fb9d81a77840360102a09fc36e54f25dbc52b7d02e52896795cd736665ae3"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.8+0/UnoUtils.v2026.2.8.x86_64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "952c184b57126bc8c24aecda1f28b5312edc0aab"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "8cfa9aa10fd41a037fe1c4b77e5ee81d52c3ec392dd6150a9c847c9af62ce0af"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.8+0/UnoUtils.v2026.2.8.x86_64-w64-mingw32-libgfortran5.tar.gz"
