[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "c1ad9b80bd5f3c0d61ad93d212880035cbf4f9d9"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2b391581ca6bd75b9a3d24f77bd72d0ef139957f4bed1683f7602df4dfeb3189"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "35a73e6d32bd8c180b908803e6cc8a108469a251"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "061ae261dd828ed7dd66ae02c9438445f1635430c920a8433e39a296c44aa27e"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.aarch64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "eed4536327d245dc88c60bcaa02a17b49afe7e69"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "2f573ea32442784635fb0b5c7c9e8bd6bec0d0496302cdb19ac436562febd850"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "e074f4acf519cff707161057cdbd7fc963f7ebf1"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "d81c63c1af9ff81a43f0c7328c733225bf2e5fa8115573ddb6f7855f0dcc4408"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "ab05a46ffa1788a56e85a81ed30d11176bc80b1e"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "7f26fd0df51b581d7c7acabeb73efd255fda2af288853815d4e0181aa0d5eb59"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.17+0/UnoUtils.v2026.2.17.x86_64-w64-mingw32-libgfortran5.tar.gz"
