[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "361ff1d601af84910618fdc6696231c1bc410a37"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "a3e8801d2deba73c58e67f9120608d425e15d42a9806e829154560483e3da849"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.9+0/UnoUtils.v2026.2.9.aarch64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "aarch64"
git-tree-sha1 = "e7f912334ec92f4ced44885edb7896559ab59109"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "db06b25eee0850fd2defa6dacf967aea26d1f619f37a86a828deaa1ab8a46d91"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.9+0/UnoUtils.v2026.2.9.aarch64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "812eadc2461acaae9cb74859a76f02523f46f154"
libgfortran_version = "5.0.0"
os = "macos"

    [[UnoUtils.download]]
    sha256 = "0e8ffb302e5897c2ca39513f283fdf5162017d1d555ecf20a0b285dd053c3c06"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.9+0/UnoUtils.v2026.2.9.x86_64-apple-darwin-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "ebc11666e8e88932296f732c2b3afbc42188258e"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[UnoUtils.download]]
    sha256 = "871c5e1f61027fc236c106091de75e4e7ae136d6eedd6590e7b5d15b67d64297"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.9+0/UnoUtils.v2026.2.9.x86_64-linux-gnu-libgfortran5.tar.gz"
[[UnoUtils]]
arch = "x86_64"
git-tree-sha1 = "b207da8ff9f066d267e9e2263ff131ca2afdff85"
libgfortran_version = "5.0.0"
os = "windows"

    [[UnoUtils.download]]
    sha256 = "3f72528e548aacbe0fa4794cf12cabe7f27951957129111f812804eb25126956"
    url = "https://github.com/amontoison/UnoUtils_jll.jl/releases/download/UnoUtils-v2026.2.9+0/UnoUtils.v2026.2.9.x86_64-w64-mingw32-libgfortran5.tar.gz"
